<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>eff</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(\b(module|class)\s.*?=\s*$|\bbegin|sig|struct|effect|(object(\s*\(_?[a-z]+\))?)\s*$|\bwhile\s.*?\bdo\s*$|\bwith\s.*?\bhandle\s*$|^let(?:\s+rec)?\s+[a-z_][a-zA-Z0-9_]*\s+(?!=)\S)</string>
	<key>foldingStopMarker</key>
	<string>(\bend(\s+in)?[ \t]*(;{1,2}|=)?|\bdone;?|^\s*;;|^\s*in)[ \t]*$</string>
	<key>keyEquivalent</key>
	<string>^~O</string>
	<key>name</key>
	<string>Eff</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.module-binding.eff</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.module-definition.eff</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.other.module.eff</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.module-binding.ocmal</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(let)\s+(module)\s+([A-Z][a-zA-Z0-9'_]*)\s*(=)</string>
			<key>name</key>
			<string>meta.module.binding</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(let|and)\s+(?!\(\*)((rec\s+)([a-z_][a-zA-Z0-9_']*)\b|([a-z_][a-zA-Z0-9_']*|\([^)]+\))(?=\s)((?=\s*=\s*(?=fun(?:ction)\b))|(?!\s*=)))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.function-definition.eff</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.other.funtion-definition.eff</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.eff</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.eff</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?:(:)\s*([^=]+))?(?:(=)|(=)\s*(?=fun(?:ction)\b))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.function.type-constraint.eff</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.eff</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.eff</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.eff</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.eff</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\(|\s)(?=fun\s)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.anonymous.eff</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.function.anonymous.eff</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function.anonymous.eff</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=(\(|\s))(fun)\s</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.function-definition.eff</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(-&gt;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.function-definition.eff</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.function.anonymous.definition.eff</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#variables</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(?=type\s)</string>
			<key>end</key>
			<string>\b(?=let|end|val)|^\s*$</string>
			<key>name</key>
			<string>meta.type-definition-group.eff</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(type|and)\s+([^=]*)(=)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.type-definition.eff</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.eff</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.type-definition.eff</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\b(type|and|let|end|val)\b)|(?=^\s*$)</string>
					<key>name</key>
					<string>meta.type-definition.eff</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#typedefs</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(with|function)(?=(\s*$|.*-&gt;))\b|((?&lt;!\S)(\|)(?=(\w|\s).*-&gt;))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.match-definition.eff</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other.function-definition.eff</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.match-definition.eff</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?:(-&gt;)|\b(when)\b|\s(?=\|))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.match-definition.eff</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.match-condition.eff</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.pattern-match.eff</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#matchpatterns</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.class-type-definition.eff</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class-type.eff</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type.eff</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^[ \t]*(class\s+type\s+)((\[\s*('[A-Za-z][a-zA-Z0-9_']*(?:\s*,\s*'[A-Za-z][a-zA-Z0-9_']*)*)\s*\]\s+)?[a-z_][a-zA-Z0-9'_]*)</string>
			<key>name</key>
			<string>meta.class.type-definition.eff</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^[ \t]*(class)(?:\s+(?!(?:virtual)\s+))((\[\s*('[A-Za-z][a-zA-Z0-9_']*(?:\s*,\s*'[A-Za-z][a-zA-Z0-9_']*)*)\s*\]\s+)?[a-z_][a-zA-Z0-9'_]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.class-definition.eff</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.eff</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type.eff</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(=)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.eff</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.class.eff</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^[ \t]*(class\s+virtual\s+)((\[\s*('[A-Za-z][a-zA-Z0-9_']*(?:\s*,\s*'[A-Za-z][a-zA-Z0-9_']*)*)\s*\]\s+)?[a-z_][a-zA-Z0-9'_]*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.class-definition.eff</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class.eff</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type.eff</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(=)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.eff</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.class.virtual.eff</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.class-type-definition.eff</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.class-type.eff</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type.eff</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^[ \t]*(class\s+type\s+virtual)((\[\s*('[A-Za-z][a-zA-Z0-9_']*(?:\s*,\s*'[A-Za-z][a-zA-Z0-9_']*)*)\s*\]\s+)?[a-z_][a-zA-Z0-9'_]*)</string>
			<key>name</key>
			<string>meta.class.virtual.type-definition.eff</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.record.eff</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.record.eff</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.record.eff</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\bwith\b</string>
					<key>name</key>
					<string>keyword.other.language.eff</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\bmutable\s+)?\b([a-z_][a-zA-Z0-9_']*)\s*(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.storage.modifier.eff</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>source.eff</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.record.eff</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;|(?=}))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.eff</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.record.definition.eff</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#typedefs</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(object)\s*(?:(\()(_?[a-z]+)(\)))?\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.object-definition.eff</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.self-binding.eff</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.self-binding.eff</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.self-binding.eff</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\b(end)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.object.eff</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.expression.eff</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.object.eff</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(method)\s+(virtual\s+)?(private\s+)?([a-z_][a-zA-Z0-9'_]*)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.method-definition.eff</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.other.method-definition.eff</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.other.method-restriction.eff</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.method.eff</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(=|:)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.eff</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.method.eff</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#variables</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(constraint)\s+([a-z_'][a-zA-Z0-9'_]*)\s+(=)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.language.eff</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.eff</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.eff</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(#[a-z_][a-zA-Z0-9'_]*)|(int|char|float|string|list|array|bool|unit|exn|option|int32|int64|nativeint|format4|lazy_t)|([a-z_][a-zA-Z0-9'_]*)\s*$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.type.polymorphic-variant.eff</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.eff</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>storage.type.eff</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.object.type-constraint.eff</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.method-call.eff</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?&lt;=\w|\)|')(#)[a-z_][a-zA-Z0-9'_]*</string>
			<key>name</key>
			<string>meta.method-call.eff</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.module-definition.eff</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.module.eff</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.module-definition.eff</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.module-type.eff</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^[ \t]*(module)\s+([A-Z_][a-zA-Z0-9'_]*)(?:\s*(:)\s*([A-Z][a-zA-Z0-9'_]*)?)?</string>
			<key>name</key>
			<string>meta.module.eff</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.module-type-definition.eff</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.module-type.eff</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^[ \t]*(module\s+type\s+)([A-Z][a-zA-Z0-9'_]*)</string>
			<key>name</key>
			<string>meta.module.type.eff</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(sig)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.module.signature.eff</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\b(end)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.module.signature.eff</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.expression.eff</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.eff</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.module.signature.eff</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#module-signature</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(struct)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.module.structure.eff</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\b(end)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.module.structure.eff</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.module.structure.eff</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#moduleref</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(open)\s+([A-Z][a-zA-Z0-9'_]*)(?=(\.[A-Z][a-zA-Z0-9_]*)*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.eff</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.other.module.eff</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\s|$)</string>
			<key>name</key>
			<string>meta.module.open.eff</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.module-reference.eff</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\.)([A-Z][a-zA-Z0-9'_]*)</string>
					<key>name</key>
					<string>support.other.module.eff</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.eff</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.exception.eff</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(exception)\s+([A-Z][a-zA-Z0-9'_]*)\b</string>
			<key>name</key>
			<string>meta.exception.eff</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?=(\[&lt;)(?![^\[]+?[^&gt;]]))</string>
			<key>end</key>
			<string>(&gt;])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.camlp4-stream.eff</string>
				</dict>
			</dict>
			<key>name</key>
			<string>source.camlp4.embedded.eff</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.camlp4.eff</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#lists</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#arrays</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\()(?=(~[a-z][a-zA-Z0-9_]*:|("(\\"|[^"])*")|[^\(\)~"])+(?&lt;!:)(:&gt;|:(?![:=])))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.type-constraint.eff</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;!:)(:&gt;|:(?![:=]))(.*?)(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.type-constraint.eff</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.eff</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.section.type-constraint.eff</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.type-constraint.eff</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>^[ \t]*#[a-zA-Z]+</string>
			<key>name</key>
			<string>keyword.other.directive.eff</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[ \t]*#[0-9]*</string>
			<key>name</key>
			<string>keyword.other.directive.line-number.eff</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storagetypes</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(mutable|ref)\b</string>
			<key>name</key>
			<string>keyword.other.storage.modifier.eff</string>
		</dict>
		<dict>
			<key>match</key>
			<string>`[A-Za-z][a-zA-Z0-9'_]*\b</string>
			<key>name</key>
			<string>entity.name.type.variant.polymorphic.eff</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[A-Z][a-zA-Z0-9'_]*\b</string>
			<key>name</key>
			<string>entity.name.type.variant.eff</string>
		</dict>
		<dict>
			<key>match</key>
			<string>!=|:=|&gt;|&lt;</string>
			<key>name</key>
			<string>keyword.operator.symbol.eff</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[*+/-]\.</string>
			<key>name</key>
			<string>keyword.operator.infix.floating-point.eff</string>
		</dict>
		<dict>
			<key>match</key>
			<string>~-\.</string>
			<key>name</key>
			<string>keyword.operator.prefix.floating-point.eff</string>
		</dict>
		<dict>
			<key>match</key>
			<string>::</string>
			<key>name</key>
			<string>punctuation.definition.list.constructor.eff</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;;</string>
			<key>name</key>
			<string>punctuation.terminator.expression.eff</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;</string>
			<key>name</key>
			<string>punctuation.separator.eff</string>
		</dict>
		<dict>
			<key>match</key>
			<string>-&gt;</string>
			<key>name</key>
			<string>punctuation.separator.function-return.eff</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[=&lt;&gt;@^&amp;+\-*/$%|][|!$%&amp;*+./:&lt;=&gt;?@^~-]*</string>
			<key>name</key>
			<string>keyword.operator.infix.eff</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bnot\b|!|[!\?~][!$%&amp;*+./:&lt;=&gt;?@^~-]+</string>
			<key>name</key>
			<string>keyword.operator.prefix.eff</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.argument-label.eff</string>
				</dict>
			</dict>
			<key>match</key>
			<string>~[a-z][a-z0-9'_]*(:)?</string>
			<key>name</key>
			<string>entity.name.tag.label.eff</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(begin)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.begin-end.eff</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\b(end)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.begin-end.eff</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.begin-end-group.eff</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(for)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.for-loop.eff</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\b(done)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.for-loop.eff</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.for-loop.eff</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\bdo\b</string>
					<key>name</key>
					<string>keyword.control.loop.eff</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(while)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.while-loop.eff</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\b(done)\b</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.while-loop.eff</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.while-loop.eff</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\bdo\b</string>
					<key>name</key>
					<string>keyword.control.loop.eff</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.paren-group.eff</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(and|land|lor|lsl|lsr|lxor|mod|or)\b</string>
			<key>name</key>
			<string>keyword.operator.eff</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(downto|if|else|handle|match|then|to|when|with|try)\b</string>
			<key>name</key>
			<string>keyword.control.eff</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(as|assert|class|constraint|exception|functor|in|include|inherit|initializer|lazy|let|mod|module|mutable|new|object|open|private|rec|sig|struct|type|virtual)\b</string>
			<key>name</key>
			<string>keyword.other.eff</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#module-signature</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(’|‘|“|”)</string>
			<key>name</key>
			<string>invalid.illegal.unrecognized-character.eff</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>arrays</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\[\|)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.array.begin.eff</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\|])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.array.end.eff</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.array.eff</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#arrays</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.block.empty.eff</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\(\*+(\*)\)</string>
					<key>name</key>
					<string>comment.block.eff</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(\*</string>
					<key>end</key>
					<string>\*\)</string>
					<key>name</key>
					<string>comment.block.eff</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?=[^\\])(")</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>comment.block.string.quoted.double.eff</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\(x[a-fA-F0-9][a-fA-F0-9]|[0-2]\d\d|[bnrt'"\\])</string>
							<key>name</key>
							<string>comment.block.string.constant.character.escape.eff</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>meta.empty-typing-pair.eff</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.empty-typing-pair.parens.eff</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>meta.empty-typing-pair.eff</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?:\[\s*(\])|\((\))|\(\s*(\)))</string>
					<key>name</key>
					<string>constant.language.pseudo-variable.eff</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(true|false)\b</string>
					<key>name</key>
					<string>constant.language.boolean.eff</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b-?[0-9][0-9_]*((\.([0-9][0-9_]*([eE][+-]??[0-9][0-9_]*)?)?)|([eE][+-]??[0-9][0-9_]*))</string>
					<key>name</key>
					<string>constant.numeric.floating-point.eff</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(-?((0(x|X)[0-9a-fA-F][0-9a-fA-F_]*)|(0(o|O)[0-7][0-7_]*)|(0(b|B)[01][01_]*)|([0-9][0-9_]*)))n</string>
					<key>name</key>
					<string>constant.numeric.integer.nativeint.eff</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(-?((0(x|X)[0-9a-fA-F][0-9a-fA-F_]*)|(0(o|O)[0-7][0-7_]*)|(0(b|B)[01][01_]*)|([0-9][0-9_]*)))L</string>
					<key>name</key>
					<string>constant.numeric.integer.int64.eff</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(-?((0(x|X)[0-9a-fA-F][0-9a-fA-F_]*)|(0(o|O)[0-7][0-7_]*)|(0(b|B)[01][01_]*)|([0-9][0-9_]*)))l</string>
					<key>name</key>
					<string>constant.numeric.integer.int32.eff</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(-?((0(x|X)[0-9a-fA-F][0-9a-fA-F_]*)|(0(o|O)[0-7][0-7_]*)|(0(b|B)[01][01_]*)|([0-9][0-9_]*)))</string>
					<key>name</key>
					<string>constant.numeric.integer.eff</string>
				</dict>
				<dict>
					<key>match</key>
					<string>'(.|\\(x[a-fA-F0-9][a-fA-F0-9]|[0-2]\d\d|[bnrt'"\\]))'</string>
					<key>name</key>
					<string>constant.character.eff</string>
				</dict>
			</array>
		</dict>
		<key>definite_storagetypes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#storagetypes</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[a-zA-Z0-9'_]+\b</string>
					<key>name</key>
					<string>storage.type.eff</string>
				</dict>
			</array>
		</dict>
		<key>lists</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\[)(?!\||&lt;|&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.list.begin.eff</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;!\||&gt;)(])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.list.end.eff</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.list.eff</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#lists</string>
						</dict>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>matchpatterns</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b_\b</string>
					<key>name</key>
					<string>constant.language.universal-match.eff</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\|(?=\s*\S)</string>
					<key>name</key>
					<string>punctuation.separator.match-pattern.eff</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()(?=(?!=.*?-&gt;).*?\|)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.match-option.eff</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.match-option.eff</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.match-option.eff</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\|</string>
							<key>name</key>
							<string>punctuation.separator.match-option.eff</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#matchpatterns</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#moduleref</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>module-signature</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(val)\s+([a-z_][a-zA-Z0-9_']*)\s*(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other.eff</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.type.value-signature.eff</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.type-constraint.eff</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\b(type|val|class|module|end)\b)|^\s*$</string>
					<key>name</key>
					<string>meta.module.signature.val.eff</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.optional-parameter.eff</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.label.optional.eff</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.optional-parameter.eff</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(\?)([a-z][a-zA-Z0-9_]*)\s*(:)</string>
							<key>name</key>
							<string>variable.parameter.ameter.optional.eff</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>([a-z][a-zA-Z0-9'_]*)\s*(:)\s*</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.label.eff</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.label.eff</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>storage.type.eff</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\s</string>
							<key>name</key>
							<string>variable.parameter.labeled.eff</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#definite_storagetypes</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#typedefs</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>moduleref</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.other.module.eff</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.module-reference.eff</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b([A-Z][a-zA-Z0-9'_]*)(\.)</string>
					<key>name</key>
					<string>meta.module-reference.eff</string>
				</dict>
			</array>
		</dict>
		<key>storagetypes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(int|char|float|string|list|array|bool|unit|exn|option|int32|int64|nativeint|format4|lazy_t)\b</string>
					<key>name</key>
					<string>storage.type.eff</string>
				</dict>
				<dict>
					<key>match</key>
					<string>#[a-z_][a-zA-Z0-9_]*</string>
					<key>name</key>
					<string>storage.type.variant.polymorphic.eff</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=[^\\])(")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.eff</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(")</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.eff</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.eff</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\$[ \t]*</string>
							<key>name</key>
							<string>punctuation.separator.string.ignore-eol.eff</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\(x[a-fA-F0-9][a-fA-F0-9]|[0-2]\d\d|[bnrt'"\\])</string>
							<key>name</key>
							<string>constant.character.string.escape.eff</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\[\|\(\)1-9$^.*+?\[\]]</string>
							<key>name</key>
							<string>constant.character.regexp.escape.eff</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\\(?!(x[a-fA-F0-9][a-fA-F0-9]|[0-2]\d\d|[bnrt'"\\]|[\|\(\)1-9$^.*+?\[\]]|$[ \t]*))(?:.)</string>
							<key>name</key>
							<string>invalid.illegal.character.string.escape</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>typedefs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\|</string>
					<key>name</key>
					<string>punctuation.separator.variant-definition.eff</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>meta.paren-group.eff</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#typedefs</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\bof\b</string>
					<key>name</key>
					<string>keyword.other.eff</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#storagetypes</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\s|\()['a-z_][a-zA-Z0-9_]*\b</string>
					<key>name</key>
					<string>storage.type.eff</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.other.module.eff</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type.module.eff</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b((?:[A-Z][a-zA-Z0-9'_]*)(?:\.[A-Z][a-zA-Z0-9'_]+)*)(\.[a-zA-Z0-9'_]+)</string>
					<key>name</key>
					<string>meta.module.type.eff</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\[(&gt;|&lt;)?)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.polymorphic-variant.eff</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\])</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.polymorphic-variant.eff</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.polymorphic-variant.definition.eff</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#typedefs</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\|</string>
					<key>name</key>
					<string>punctuation.separator.algebraic-type.eff</string>
				</dict>
			</array>
		</dict>
		<key>variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\(\)</string>
					<key>name</key>
					<string>variable.parameter.unit.eff</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#moduleref</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(~)([a-z][a-zA-Z0-9'_]*)(\s*:\s*)?</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.labeled-parameter.eff</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.label.eff</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.label.eff</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=(-&gt;|\s))</string>
					<key>name</key>
					<string>variable.parameter.labeled.eff</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#variables</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.optional-parameter.eff</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.label.optional.eff</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\?)([a-z][a-zA-Z0-9_]*)</string>
					<key>name</key>
					<string>variable.parameter.optional.eff</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\?)(\()([a-z_][a-zA-Z0-9'_]*)\s*(=)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.optional-parameter.eff</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.optional-parameter.eff</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.tag.label.optional.eff</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.optional-parameter-assignment.eff</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.optional-parameter.eff</string>
						</dict>
					</dict>
					<key>name</key>
					<string>variable.parameter.optional.eff</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()(?=(~[a-z][a-zA-Z0-9_]*:|("(\\"|[^"])*")|[^\(\)~"])+(?&lt;!:)(:&gt;|:(?![:=])))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.type-constraint.eff</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.type-constraint.eff</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.parameter.type-constrained.eff</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(?&lt;!:)(:&gt;|:(?![:=]))</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.type-constraint.eff</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=\))</string>
							<key>name</key>
							<string>storage.type.eff</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>\(</string>
									<key>end</key>
									<string>\)</string>
									<key>name</key>
									<string>meta.paren.group</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#variables</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>meta.paren-group.eff</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#variables</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tuple.eff</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.tuple.eff</string>
						</dict>
					</dict>
					<key>name</key>
					<string>variable.parameter.tuple.eff</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#matchpatterns</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#variables</string>
						</dict>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>punctuation.separator.tuple.eff</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.record.eff</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.record.eff</string>
						</dict>
					</dict>
					<key>name</key>
					<string>variable.parameter.record.eff</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#moduleref</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\b([a-z][a-zA-Z0-9'_]*)\s*(=)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.record.eff</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.record.field-assignment.eff</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(;)|(?=\})</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.record.eff</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.recordfield.match.eff</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#matchpatterns</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#storagetypes</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b[a-z_][a-zA-Z0-9'_]*</string>
					<key>name</key>
					<string>variable.parameter.eff</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.eff</string>
	<key>uuid</key>
	<string>F816FA69-6EE8-11D9-BF2D-000D93589AF6</string>
</dict>
</plist>
