#!/bin/bash
# WARNING: Do not change this file without making sure that sed in Makefile still works
BASEDIR=.
# Look for a line-editing wrapper rlwrap or ledit
if [ -x /usr/bin/which ]
then
    WRAPPER=`/usr/bin/which rlwrap`
    if [ "$WRAPPER" = "" ]
    then
       WRAPPER=`/usr/bin/which ledit`
    fi
else
    WRAPPER=""
fi
# Determine whether we are going to run native or bytecode eff
if [ -x "$BASEDIR/eff.native" ]
then
  EFF="$BASEDIR/eff.native"
elif [ -x "$BASEDIR/eff.byte" ]
then
  EFF="$BASEDIR/eff.byte"
else
  echo "Cannot find the eff executable in $BASEDIR"
  exit 1
fi
# Execute eff
if [ "$WRAPPER" != "" ]
then
  exec "$WRAPPER" "$EFF" --pervasives "$BASEDIR/pervasives.eff" $@
else
  exec "$EFF" --pervasives "$BASEDIR/pervasives.eff" $@
fi
