let f9 = fun (x) -> (x)
in let f8 = fun (x) -> (((fun (coer_x1) -> (fun (coer_x2) -> ((fun (x) -> (x)) ((coer_x1) ((fun (x) -> (x)) (coer_x2)))))) (f9)) (x))
in let f7 = fun (x) -> (((fun (coer_x1) -> (fun (coer_x2) -> ((fun (x) -> (x)) ((coer_x1) ((fun (x) -> (x)) (coer_x2)))))) (f8)) (x))
in let f6 = fun (x) -> (((fun (coer_x1) -> (fun (coer_x2) -> ((fun (x) -> (x)) ((coer_x1) ((fun (x) -> (x)) (coer_x2)))))) (f7)) (x))
in let f5 = fun (x) -> (((fun (coer_x1) -> (fun (coer_x2) -> ((fun (x) -> (x)) ((coer_x1) ((fun (x) -> (x)) (coer_x2)))))) (f6)) (x))
in let f4 = fun (x) -> (((fun (coer_x1) -> (fun (coer_x2) -> ((fun (x) -> (x)) ((coer_x1) ((fun (x) -> (x)) (coer_x2)))))) (f5)) (x))
in let f3 = fun (x) -> (((fun (coer_x1) -> (fun (coer_x2) -> ((fun (x) -> (x)) ((coer_x1) ((fun (x) -> (x)) (coer_x2)))))) (f4)) (x))
in let f2 = fun (x) -> (((fun (coer_x1) -> (fun (coer_x2) -> ((fun (x) -> (x)) ((coer_x1) ((fun (x) -> (x)) (coer_x2)))))) (f3)) (x))
in let f1 = fun (x) -> (((fun (coer_x1) -> (fun (coer_x2) -> ((fun (x) -> (x)) ((coer_x1) ((fun (x) -> (x)) (coer_x2)))))) (f2)) (x))
in ((fun (coer_x1) -> (fun (coer_x2) -> ((fun (x) -> (x)) ((coer_x1) ((fun (x) -> (x)) (coer_x2)))))) (f1)) (3)
