name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14.x

      - name: Install Opam packages
        run: opam pin add -n .; opam install eff --deps-only

      - name: Test
        run: opam exec -- make test
      
      - name: Delete problematic files
        run: rm -rf misc tests
      
      - name: Build
        run: opam exec -- make release

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
